import { useEffect, useState } from 'react';
import api from '../services/api';

const statuses = ['Pending', 'Confirmed', 'Completed', 'Cancelled'];

export default function AdminConsole() {
  const [tab, setTab] = useState('dashboard');
  const [tests, setTests] = useState([]);
  const [bookings, setBookings] = useState([]);
  const [error, setError] = useState('');
  const [newTest, setNewTest] = useState({ name: '', price: '', category: 'Laboratory', description: '' });
  const load = () => Promise.all([api.get('/tests?includeUnavailable=true'), api.get('/admin/bookings')]).then(([testResult, bookingResult]) => { setTests(testResult.data.tests); setBookings(bookingResult.data.bookings); }).catch((err) => setError(err.response?.data?.message || 'Could not load admin data.'));
  useEffect(() => { load(); }, []);
  const addTest = async (event) => { event.preventDefault(); try { await api.post('/admin/tests', { ...newTest, price: Number(newTest.price) }); setNewTest({ name: '', price: '', category: 'Laboratory', description: '' }); load(); } catch (err) { setError(err.response?.data?.message || 'Could not add test.'); } };
  const toggle = async (test) => { await api.put(`/admin/tests/${test._id}`, { isAvailable: !test.isAvailable }); load(); };
  const changeStatus = async (bookingId, status) => { await api.put(`/admin/bookings/${bookingId}`, { status }); load(); };
  const available = tests.filter((test) => test.isAvailable).length;
  const pending = bookings.filter((booking) => booking.status === 'Pending').length;
  return <div className="container py-5"><h1>Admin Dashboard</h1><p className="text-muted">Centre-wide booking and test management.</p>{error && <div className="alert alert-danger">{error}</div>}<div className="d-flex flex-wrap gap-2 mb-4"><Tab active={tab === 'dashboard'} onClick={() => setTab('dashboard')}>Dashboard</Tab><Tab active={tab === 'tests'} onClick={() => setTab('tests')}>Manage Tests</Tab><Tab active={tab === 'bookings'} onClick={() => setTab('bookings')}>Manage Bookings</Tab></div>{tab === 'dashboard' && <><div className="row g-3"><Metric label="Available tests" value={available}/><Metric label="Disabled tests" value={tests.length - available}/><Metric label="Total bookings" value={bookings.length}/><Metric label="Pending bookings" value={pending}/></div><h2 className="h4 mt-5">Recent Patient Bookings</h2><Bookings bookings={bookings.slice(0, 5)} onChange={changeStatus}/></>}{tab === 'tests' && <div className="row g-4"><div className="col-lg-4"><form className="bg-white border rounded p-4" onSubmit={addTest}><h2 className="h4">Add Test</h2>{Object.entries(newTest).map(([key, value]) => <input key={key} required className="form-control mb-2" type={key === 'price' ? 'number' : 'text'} placeholder={key} value={value} onChange={(event) => setNewTest({ ...newTest, [key]: event.target.value })}/>)}<button className="btn btn-primary w-100">Add Test</button></form></div><div className="col-lg-8"><h2 className="h4">All Tests</h2>{tests.map((test) => <div className="d-flex gap-2 align-items-center border-bottom py-2" key={test._id}><span className="flex-grow-1">{test.name} — ₹{test.price} {!test.isAvailable && <em className="text-muted">(disabled)</em>}</span><button className="btn btn-sm btn-outline-secondary" onClick={() => toggle(test)}>{test.isAvailable ? 'Disable' : 'Enable'}</button></div>)}</div></div>}{tab === 'bookings' && <><h2 className="h4">All Patient Bookings</h2><Bookings bookings={bookings} onChange={changeStatus}/></>}</div>;
}
function Tab({ active, onClick, children }) { return <button className={`btn ${active ? 'btn-primary' : 'btn-outline-primary'}`} onClick={onClick}>{children}</button>; }
function Metric({ label, value }) { return <div className="col-sm-6 col-lg"><div className="stat-card h-100"><span>{label}</span><strong>{value}</strong></div></div>; }
function Bookings({ bookings, onChange }) { return <div className="table-responsive"><table className="table align-middle"><thead><tr><th>Patient</th><th>Test</th><th>Date</th><th>Status</th></tr></thead><tbody>{bookings.map((booking) => <tr key={booking._id}><td>{booking.patientName}<br/><small>{booking.phone}</small></td><td>{booking.testName}<br/>₹{booking.price}</td><td>{new Date(booking.testDate).toLocaleDateString()}</td><td><select className="form-select form-select-sm" value={booking.status} onChange={(event) => onChange(booking._id, event.target.value)}>{statuses.map((status) => <option key={status}>{status}</option>)}</select></td></tr>)}</tbody></table>{!bookings.length && <p className="text-muted">No bookings yet.</p>}</div>; }
