import { useEffect, useState } from 'react';
import api from '../services/api';

const statuses = ['Pending', 'Confirmed', 'Completed', 'Cancelled'];
const categories = ['Laboratory', 'Hematology', 'Microbiology', 'Biochemistry', 'Immunology', 'Serology', 'Diabetes', 'Profile', 'Hormone', 'Pathology', 'Cardiology', 'Vitamin', 'Imaging'];
const blankTest = { name: '', price: '', category: 'Laboratory', description: '', isAvailable: true };

export default function AdminConsoleV2() {
  const [tab, setTab] = useState('dashboard');
  const [tests, setTests] = useState([]);
  const [bookings, setBookings] = useState([]);
  const [newTest, setNewTest] = useState(blankTest);
  const [editingTest, setEditingTest] = useState(null);
  const [error, setError] = useState('');

  const load = () => Promise.all([api.get('/tests?includeUnavailable=true'), api.get('/admin/bookings')]).then(([testResult, bookingResult]) => { setTests(testResult.data.tests); setBookings(bookingResult.data.bookings); }).catch((err) => setError(err.response?.data?.message || 'Could not load admin data.'));
  useEffect(() => { load(); }, []);

  const addTest = async (event) => { event.preventDefault(); setError(''); try { await api.post('/admin/tests', { ...newTest, price: Number(newTest.price) }); setNewTest(blankTest); load(); } catch (err) { setError(err.response?.data?.message || 'Could not add test.'); } };
  const saveEdit = async (event) => { event.preventDefault(); setError(''); try { const { _id, createdAt, updatedAt, __v, ...values } = editingTest; await api.put(`/admin/tests/${_id}`, { ...values, price: Number(values.price) }); setEditingTest(null); load(); } catch (err) { setError(err.response?.data?.message || 'Could not update test.'); } };
  const toggle = async (test) => { try { await api.put(`/admin/tests/${test._id}`, { isAvailable: !test.isAvailable }); load(); } catch (err) { setError(err.response?.data?.message || 'Could not update test.'); } };
  const remove = async (test) => { if (!window.confirm(`Delete ${test.name} permanently?`)) return; try { await api.delete(`/admin/tests/${test._id}`); load(); } catch (err) { setError(err.response?.data?.message || 'Could not delete test.'); } };
  const changeStatus = async (id, status) => { try { await api.put(`/admin/bookings/${id}`, { status }); load(); } catch (err) { setError(err.response?.data?.message || 'Could not update booking.'); } };

  const available = tests.filter((test) => test.isAvailable).length;
  const pending = bookings.filter((booking) => booking.status === 'Pending').length;
  return <div className="container py-5"><h1>Admin Dashboard</h1><p className="text-muted">Centre-wide booking and test management.</p>{error && <div className="alert alert-danger">{error}</div>}<div className="d-flex flex-wrap gap-2 mb-4"><Tab active={tab === 'dashboard'} onClick={() => setTab('dashboard')}>Dashboard</Tab><Tab active={tab === 'tests'} onClick={() => setTab('tests')}>Manage Tests</Tab><Tab active={tab === 'bookings'} onClick={() => setTab('bookings')}>Manage Bookings</Tab></div>{tab === 'dashboard' && <><div className="row g-3"><Metric label="Available tests" value={available}/><Metric label="Disabled tests" value={tests.length - available}/><Metric label="Total bookings" value={bookings.length}/><Metric label="Pending bookings" value={pending}/></div><h2 className="h4 mt-5">Recent Patient Bookings</h2><Bookings bookings={bookings.slice(0, 5)} onChange={changeStatus}/></>}{tab === 'tests' && <div className="row g-4"><div className="col-lg-4"><TestForm title="Add Test" value={newTest} onChange={setNewTest} onSubmit={addTest} submitLabel="Add Test"/></div><div className="col-lg-8"><h2 className="h4">All Tests</h2>{tests.map((test) => <div className="d-flex flex-wrap gap-2 align-items-center border-bottom py-2" key={test._id}><span className="flex-grow-1">{test.name} — ₹{test.price} {!test.isAvailable && <em className="text-muted">(disabled)</em>}</span><button className="btn btn-sm btn-outline-primary" onClick={() => setEditingTest({ ...test })}>Edit</button><button className="btn btn-sm btn-outline-secondary" onClick={() => toggle(test)}>{test.isAvailable ? 'Disable' : 'Enable'}</button><button className="btn btn-sm btn-outline-danger" onClick={() => remove(test)}>Delete</button></div>)}</div></div>}{tab === 'bookings' && <><h2 className="h4">All Patient Bookings</h2><Bookings bookings={bookings} onChange={changeStatus}/></>}{editingTest && <div className="booking-modal active" role="presentation"><div className="booking-box" role="dialog" aria-modal="true" aria-labelledby="editTestTitle"><button className="close-btn" type="button" aria-label="Close edit form" onClick={() => setEditingTest(null)}>&times;</button><TestForm title="Edit Test" value={editingTest} onChange={setEditingTest} onSubmit={saveEdit} submitLabel="Save Changes"/></div></div>}</div>;
}

function Tab({ active, onClick, children }) { return <button className={`btn ${active ? 'btn-primary' : 'btn-outline-primary'}`} onClick={onClick}>{children}</button>; }
function Metric({ label, value }) { return <div className="col-sm-6 col-lg"><div className="stat-card h-100"><span>{label}</span><strong>{value}</strong></div></div>; }
function TestForm({ title, value, onChange, onSubmit, submitLabel }) { const field = (key, type = 'text') => <input required type={type} className="form-control mb-2" placeholder={key} value={value[key] ?? ''} onChange={(event) => onChange({ ...value, [key]: event.target.value })}/>; return <form className="bg-white border rounded p-4" onSubmit={onSubmit}><h2 id={title === 'Edit Test' ? 'editTestTitle' : undefined} className="h4">{title}</h2>{field('name')}{field('price', 'number')}<select required className="form-select mb-2" value={value.category ?? 'Laboratory'} onChange={(event) => onChange({ ...value, category: event.target.value })}>{categories.map((category) => <option key={category}>{category}</option>)}</select>{field('description')}<label className="form-check mb-3"><input className="form-check-input" type="checkbox" checked={value.isAvailable} onChange={(event) => onChange({ ...value, isAvailable: event.target.checked })}/><span className="form-check-label">Available for booking</span></label><button className="btn btn-primary w-100">{submitLabel}</button></form>; }
function Bookings({ bookings, onChange }) { return <div className="table-responsive"><table className="table align-middle"><thead><tr><th>Patient</th><th>Test</th><th>Appointment</th><th>Booked on</th><th>Status</th></tr></thead><tbody>{bookings.map((booking) => <tr key={booking._id}><td>{booking.patientName}<br/><small>{booking.phone}</small></td><td>{booking.testName}<br/>₹{booking.price}</td><td>{new Date(booking.testDate).toLocaleString()}</td><td>{new Date(booking.createdAt).toLocaleString()}</td><td><select className="form-select form-select-sm" value={booking.status} onChange={(event) => onChange(booking._id, event.target.value)}>{statuses.map((status) => <option key={status}>{status}</option>)}</select></td></tr>)}</tbody></table>{!bookings.length && <p className="text-muted">No bookings yet.</p>}</div>; }
